### ISSUE TITLE
Access control

### ISSUE THREAD

**Issue by shak-mar** [jaseg/matelight#7]
If I remember right, the matelight setup at Jugend Hackt Berlin allowed for lots of data being sent over UDP, blocking access for everyone that tries to write text over TCP.  (Please correct me if this is just my imagination.)

My Idea: Create a queue that is used to buffer the frames until they are displayed.  Make sure this queue never stores more frames than what’s needed for X, by dropping every received frame until the queue has frames for less than Y.

The timings X and Y should be configurable.

**Comment by jaseg** [comment]
There is some access control in the codebase as-is, which works as follows:
 * Any messages recevied via TCP are queued to be displayed one after another.
 * If an UDP stream is opened, TCP message displaying is paused (further incoming messages continue to be queued) and the UDP stream is displayed.
 * If another UDP stream is opened, it is enqueued
 * When one UDP stream closes (signalled by a 3-second timeout), the next one is selected.
 * If no further UDP streams are available, TCP message displaying is resumed.
 * If the TCP message queue is empty, "screensaver" messages are read and displayed from a file on the control computer.

**Comment by shak-mar** [comment]
This kind of “access control” only works if you don’t want to make sure everyone has an equal chance to display things.  Situations like at Jugend Hackt Berlin are exceptions, so I can understand if you choose to leave it as it is.

**Comment by jaseg** [comment]
I think I don't understand your queueing concept then, because I don't understand what you would gain in that regard. What would be ``X`` and ``Y``? Would this queue be global? Would it encompass TCP and UDP data or only UDP data?

**Comment by shak-mar** [comment]
It would store both frames received via UDP and frames generated by text received via TCP.  Once the text is converted to frames, both sources would be treated equally. `X` and `Y` could be 30 and 10 seconds, as an example.  If someone wants to send something, the maximum length would be 30 seconds.  As soon as the queue is 30 seconds long, it would ignore everything for 20 seconds (`X` - `Y`).  This would make sure noone can block the access for too long.  I would propose much longer durations for `X` and `Y` though.

**Comment by jaseg** [comment]
Ah, now I see what you mean. I like the idea, I'll look into it tonight. Thanks!

**Comment by jaseg** [comment]
Ok, I just pushed a three-line patch to master that will cause it to randomly choose a new UDP client every 30 seconds as long as there is more than one sending. It would be possible to adapt this to use a proper queue, if you are interested you are welcome to send a PR :)

**Comment by shak-mar** [comment]
Well, I wouldn’t have the hardware required to test it anyways...

**Comment by jaseg** [comment]
I'm closing this now, we recently had an installation at 32C3 and it worked fine there with that patch applied.
